"""
Routers module initialization.
"""
from app.routers import (
    auth,
    restaurants,
    farmers,
    products,
    orders,
    consumer_orders,
    consumers,
    favorites,
    upload,
    producer,
    settings,
    logistics,
    admin_auth,
    admin_users,
    admin_delivery_slots,
    delivery_schedules,
    delivery_slots,
    guest,
    admin_guest,
)

__all__ = [
    "auth",
    "restaurants",
    "farmers",
    "products",
    "orders",
    "consumer_orders",
    "consumers",
    "favorites",
    "upload",
    "producer",
    "settings",
    "logistics",
    "admin_auth",
    "admin_users",
    "admin_delivery_slots",
    "delivery_schedules",
    "delivery_slots",
    "guest",
    "admin_guest",
]
