"""Initial migration

Revision ID: 20e869140d4e
Revises: 
Create Date: 2025-12-07 23:30:57.540312+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20e869140d4e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='生産者ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='生産者名'),
    sa.Column('main_crop', sa.String(length=200), nullable=True, comment='主要作物'),
    sa.Column('profile_photo_url', sa.String(length=500), nullable=True, comment='顔写真URL'),
    sa.Column('bio', sa.Text(), nullable=True, comment='プロフィール・紹介文'),
    sa.Column('map_url', sa.String(length=500), nullable=True, comment='農園MAPリンク (外部サイト)'),
    sa.Column('email', sa.String(length=200), nullable=True, comment='メールアドレス'),
    sa.Column('phone_number', sa.String(length=20), nullable=True, comment='電話番号'),
    sa.Column('address', sa.String(length=500), nullable=True, comment='農園所在地'),
    sa.Column('farming_method', sa.String(length=200), nullable=True, comment='栽培方法 (有機, 減農薬など)'),
    sa.Column('certifications', sa.String(length=500), nullable=True, comment='認証情報 (JAS有機など)'),
    sa.Column('latitude', sa.String(length=50), nullable=True, comment='緯度'),
    sa.Column('longitude', sa.String(length=50), nullable=True, comment='経度'),
    sa.Column('kodawari', sa.String(length=1000), nullable=True, comment='農家のこだわり'),
    sa.Column('selectable_days', sa.String(length=100), nullable=True, comment='選択可能曜日 (JSON: [0,1,2...])'),
    sa.Column('article_url', sa.String(length=500), nullable=True, comment='記事URL (JSON Array)'),
    sa.Column('video_url', sa.String(length=500), nullable=True, comment='動画URL (JSON Array)'),
    sa.Column('is_active', sa.Integer(), nullable=False, comment='アクティブフラグ (0: 無効, 1: 有効)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新日時'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='削除日時'),
    sa.PrimaryKeyConstraint('id'),
    comment='生産者テーブル'
    )
    op.create_index(op.f('ix_farmers_id'), 'farmers', ['id'], unique=False)
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='飲食店ID'),
    sa.Column('line_user_id', sa.String(length=100), nullable=False, comment='LINE User ID (認証用)'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='店舗名'),
    sa.Column('phone_number', sa.String(length=20), nullable=False, comment='電話番号 (緊急連絡用)'),
    sa.Column('address', sa.String(length=500), nullable=False, comment='住所 (納品先)'),
    sa.Column('invoice_email', sa.String(length=200), nullable=True, comment='請求書送付先メールアドレス'),
    sa.Column('business_hours', sa.String(length=200), nullable=True, comment='営業時間'),
    sa.Column('notes', sa.String(length=1000), nullable=True, comment='備考・特記事項'),
    sa.Column('is_active', sa.Integer(), nullable=False, comment='アクティブフラグ (0: 無効, 1: 有効)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新日時'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='削除日時'),
    sa.PrimaryKeyConstraint('id'),
    comment='飲食店テーブル'
    )
    op.create_index(op.f('ix_restaurants_id'), 'restaurants', ['id'], unique=False)
    op.create_index(op.f('ix_restaurants_line_user_id'), 'restaurants', ['line_user_id'], unique=True)
    op.create_index('ix_restaurants_line_user_id_active', 'restaurants', ['line_user_id', 'is_active'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='注文ID'),
    sa.Column('restaurant_id', sa.Integer(), nullable=False, comment='飲食店ID'),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=False, comment='配送希望日'),
    sa.Column('delivery_time_slot', sa.Enum('SLOT_12_14', 'SLOT_14_16', 'SLOT_16_18', name='deliverytimeslot'), nullable=False, comment='配送時間枠 (12-14, 14-16, 16-18)'),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'PREPARING', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=False, comment='注文ステータス'),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False, comment='小計 (税抜)'),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='消費税額'),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='合計金額 (税込)'),
    sa.Column('delivery_address', sa.String(length=500), nullable=False, comment='配送先住所'),
    sa.Column('delivery_phone', sa.String(length=20), nullable=False, comment='配送先電話番号'),
    sa.Column('delivery_notes', sa.Text(), nullable=True, comment='配送メモ・要望'),
    sa.Column('notes', sa.Text(), nullable=True, comment='注文メモ'),
    sa.Column('invoice_url', sa.String(length=500), nullable=True, comment='請求書PDF URL'),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True, comment='受注確定日時'),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True, comment='配送開始日時'),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True, comment='配達完了日時'),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True, comment='キャンセル日時'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='注文テーブル'
    )
    op.create_index(op.f('ix_orders_delivery_date'), 'orders', ['delivery_date'], unique=False)
    op.create_index('ix_orders_delivery_date_status', 'orders', ['delivery_date', 'status'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_restaurant_id'), 'orders', ['restaurant_id'], unique=False)
    op.create_index('ix_orders_restaurant_status', 'orders', ['restaurant_id', 'status'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='商品ID'),
    sa.Column('farmer_id', sa.Integer(), nullable=True, comment='生産者ID (市場品はNULL)'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='商品名'),
    sa.Column('description', sa.Text(), nullable=True, comment='商品説明'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='単価 (税抜)'),
    sa.Column('tax_rate', sa.Enum('STANDARD', 'REDUCED', name='taxrate'), nullable=False, comment='税率 (8% or 10%)'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='単位 (個, kg, パックなど)'),
    sa.Column('stock_type', sa.Enum('KOBE', 'OTHER', name='stocktype'), nullable=False, comment='種別 (KOBE: 神戸野菜, OTHER: その他の野菜)'),
    sa.Column('category', sa.Enum('LEAFY', 'ROOT', 'FRUIT_VEG', 'MUSHROOM', 'HERB', 'OTHER', name='productcategory'), nullable=True, comment='カテゴリ (葉物, 根菜など)'),
    sa.Column('stock_quantity', sa.Integer(), nullable=True, comment='在庫数 (神戸野菜のみ管理)'),
    sa.Column('image_url', sa.String(length=500), nullable=True, comment='商品画像URL'),
    sa.Column('media_url', sa.String(length=500), nullable=True, comment='動画・POP素材URL'),
    sa.Column('is_active', sa.Integer(), nullable=False, comment='販売可否 (0: 販売停止, 1: 販売中)'),
    sa.Column('is_featured', sa.Integer(), nullable=False, comment='おすすめフラグ (0: 通常, 1: おすすめ)'),
    sa.Column('display_order', sa.Integer(), nullable=False, comment='表示順序'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新日時'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='削除日時'),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='商品テーブル'
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index('ix_products_category_active', 'products', ['category', 'is_active'], unique=False)
    op.create_index(op.f('ix_products_farmer_id'), 'products', ['farmer_id'], unique=False)
    op.create_index('ix_products_farmer_id_active', 'products', ['farmer_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_stock_type'), 'products', ['stock_type'], unique=False)
    op.create_index('ix_products_stock_type_active', 'products', ['stock_type', 'is_active'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='お気に入りID'),
    sa.Column('restaurant_id', sa.Integer(), nullable=False, comment='飲食店ID'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='商品ID'),
    sa.Column('notes', sa.Integer(), nullable=True, comment='メモ・備考'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'product_id', name='uq_restaurant_product'),
    comment='お気に入りテーブル'
    )
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.create_index('ix_favorites_product_id', 'favorites', ['product_id'], unique=False)
    op.create_index('ix_favorites_restaurant_id', 'favorites', ['restaurant_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='注文明細ID'),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='注文ID'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='商品ID'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='数量'),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='単価 (税抜・スナップショット)'),
    sa.Column('tax_rate', sa.Integer(), nullable=False, comment='税率 (スナップショット)'),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False, comment='小計 (税抜)'),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='消費税額'),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='合計金額 (税込)'),
    sa.Column('product_name', sa.String(length=200), nullable=False, comment='商品名 (スナップショット)'),
    sa.Column('product_unit', sa.String(length=20), nullable=False, comment='単位 (スナップショット)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='注文明細テーブル'
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index('ix_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index('ix_order_items_order_id', table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_favorites_restaurant_id', table_name='favorites')
    op.drop_index('ix_favorites_product_id', table_name='favorites')
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index('ix_products_stock_type_active', table_name='products')
    op.drop_index(op.f('ix_products_stock_type'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index('ix_products_farmer_id_active', table_name='products')
    op.drop_index(op.f('ix_products_farmer_id'), table_name='products')
    op.drop_index('ix_products_category_active', table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index('ix_orders_restaurant_status', table_name='orders')
    op.drop_index(op.f('ix_orders_restaurant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index('ix_orders_delivery_date_status', table_name='orders')
    op.drop_index(op.f('ix_orders_delivery_date'), table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_restaurants_line_user_id_active', table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_line_user_id'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_id'), table_name='restaurants')
    op.drop_table('restaurants')
    op.drop_index(op.f('ix_farmers_id'), table_name='farmers')
    op.drop_table('farmers')
    # ### end Alembic commands ###
