"""add image url columns to consumers and guest interactions

Revision ID: ff4a877946e5
Revises: b29988a2a962
Create Date: 2026-01-19 23:06:17.851472+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff4a877946e5'
down_revision: Union[str, None] = 'b29988a2a962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumers', sa.Column('profile_image_url', sa.String(length=500), nullable=True, comment='プロフィール画像URL'))
    op.add_column('guest_interactions', sa.Column('user_image_url', sa.String(length=500), nullable=True, comment='ユーザーのプロフィール画像URL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guest_interactions', 'user_image_url')
    op.drop_column('consumers', 'profile_image_url')
    # ### end Alembic commands ###
