ALTER TABLE products ADD COLUMN IF NOT EXISTS is_outlet INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE farmers ADD COLUMN IF NOT EXISTS article_url VARCHAR(500) NULL;
ALTER TABLE farmers ADD COLUMN IF NOT EXISTS video_url VARCHAR(500) NULL;
ALTER TABLE farmers ADD COLUMN IF NOT EXISTS kodawari VARCHAR(1000) NULL;
